Project1/force-app/main/default/objects/Quest__c/Quest__c.object-meta.xml
<CustomObject>
    <label>Quest</label>
    <nameField>
        <label>Quest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Quest__c/fields/Danger_Level__c.field-meta.xml
<CustomField>
    <fullName>Danger_Level__c</fullName>
    <description>This field describes the difficulty of a quest.</description>
    <label>Danger Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certain Death</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Beginner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Date_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Opened__c</fullName>
    <description>The date that quest became available for completion.</description>
    <label>Date Opened</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_City__c.field-meta.xml
<CustomField>
    <fullName>Quest_City__c</fullName>
    <description>The city affiliated with this quest.</description>
    <label>Quest City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quest__c/fields/Quest_Country__c.field-meta.xml
<CustomField>
    <fullName>Quest_Country__c</fullName>
    <description>The country affiliated with this quest.</description>
    <label>Quest Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quest__c/fields/Quest_Details__c.field-meta.xml
<CustomField>
    <fullName>Quest_Details__c</fullName>
    <label>Quest Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Quest_Postal_Code__c</fullName>
    <description>The postal code of the quest-giver.</description>
    <label>Quest Postal Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_State__c.field-meta.xml
<CustomField>
    <fullName>Quest_State__c</fullName>
    <description>The home state of the quest-giver.</description>
    <label>Quest State</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_Street__c.field-meta.xml
<CustomField>
    <fullName>Quest_Street__c</fullName>
    <description>The street address of the quest-giver.</description>
    <label>Quest Street</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Required_Professions__c.field-meta.xml
<CustomField>
    <fullName>Required_Professions__c</fullName>
    <label>Required Professions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventurer</fullName>
            </value>
            <value>
                <fullName>Craftsman</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Requires_Party__c.field-meta.xml
<CustomField>
    <fullName>Requires_Party__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Party</label>
    <type>Checkbox</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <description>The sub-status of a quest&apos;s completion.</description>
    <label>Sub-Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Never</fullName>
            </value>
            <value>
                <fullName>Gonna</fullName>
            </value>
            <value>
                <fullName>Give</fullName>
            </value>
            <value>
                <fullName>You</fullName>
            </value>
            <value>
                <fullName>Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/classes/QuestExtension.cls
public class QuestExtension {
    
    public String questId {get; set;}
    public transient Boolean hasError {get; set;}
    public transient String errorMessage {get; set;}
    public QuestFormData formData {get; set;}
    
    private final String approvalProcessName = 'Approve_Quest_Application';
    
    public QuestExtension(ApexPages.StandardSetController ssc) {
        ssc.setPageSize(10);
        hasError = false;
        formData = new QuestFormData();
    }
    
    // @desc: get the description of a quest
    public String getDescription() {
        if(questId == null) {
        	return 'Select a quest from the left to see its information here';
        }
        
        Quest__c q = [SELECT Quest_Details__c From Quest__c WHERE Id = :questId];
        return q.Quest_Details__c;
    }
    
    // @desc: get the title of a quest
    public String getTitle() {
        if(questId == null) {
            return 'Quest Panel';
        }
        
        Quest__c q = [SELECT Name From Quest__c WHERE Id = :questId];
        return q.Name;
    }
    
    // @desc: submit a quest for approval
    public void submitForApproval() {
        if(questId == null) return;
        
        Approval.ProcessSubmitRequest questApprovalRequest = new Approval.ProcessSubmitRequest();
        questApprovalRequest.setObjectId(questId);
        questApprovalRequest.submitterid = UserInfo.getUserId();
        questApprovalRequest.setProcessDefinitionNameOrId(approvalProcessName);
         
        try {
        	Approval.process(questApprovalRequest);
        } catch(Exception e) {
            System.debug(e);
            hasError = true;
            // query for the quest and figure out why we failed
            Quest__c q = [SELECT Status__c, Sub_Status__c FROM Quest__c WHERE Id = :questId ];
            
            // if the quest has already been accepted by some player
            if(q.Status__c == 'Open' && q.Sub_Status__c == 'Accepted') {
                errorMessage = 'This quest has already been accepted by some user. Please try another quest.';
            } 
            
            // if something else happened
            else {
            	errorMessage = 'Unable to submit quest for approval. Please try another quest.';
            }
        } finally {
        	questId = null;
        }
    } 
    
    // @desc : this function allows us to dynamically create a new quest from the quest page
    public void saveQuest() {
        System.debug(formData);
        
        Quest__c newQuest = new Quest__c();
        newQuest.Name = formData.questName;
        newQuest.Danger_Level__c = formData.dangerLevel;
        newQuest.Location__c = formData.location;
        newQuest.Requires_Party__c = formData.requiresParty;
        newQuest.Quest_Details__c = formData.questDetails;
        newQuest.Reward__c = formData.reward;
        
        if(formData.requiredProfessionAdventurer && formData.requiredProfessionCraftsman) {
            newQuest.Required_Professions__c = 'Adventurer,Craftsman';
        } else if(formData.requiredProfessionAdventurer) {
            newQuest.Required_Professions__c = 'Adventurer';
        } else if(formData.requiredProfessionCraftsman) {
            newQuest.Required_Professions__c = 'Craftsman';
        }
        
        // standard stuff
        newQuest.Status__c = 'New';
        newQuest.Sub_Status__c = 'Pending';
        newQuest.Date_Opened__c = Date.today();
        
        // deprecated, but needed for now
        newQuest.Quest_Country__c = 'USA';
        newQuest.Quest_City__c = 'Baltimore';
        newQuest.Quest_Postal_Code__c = '20740';
        newQuest.Quest_Street__c = '123 main ave';
        newQuest.Quest_State__c = 'Maryland';
        
        try {
            insert newQuest;
        } catch(DMLException e) {
			System.debug(e);
        } catch(Exception e) {
        	System.debug(e);
        } finally {
      	
            formData = new QuestFormData();
        }        
    }
}