Project1/force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Artificer_Level__c.field-meta.xml
<CustomField>
    <fullName>Artificer_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Artificer Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Member_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Member Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/Quest__c.object-meta.xml
<CustomObject>
    <label>Quest</label>
    <nameField>
        <label>Quest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Quest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quests</relationshipLabel>
    <relationshipName>Quests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Danger_Level__c.field-meta.xml
<CustomField>
    <fullName>Danger_Level__c</fullName>
    <description>This field describes the difficulty of a quest.</description>
    <label>Danger Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certain Death</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Beginner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Date_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Opened__c</fullName>
    <description>The date that quest became available for completion.</description>
    <label>Date Opened</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Quests</relationshipLabel>
    <relationshipName>Quests</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_City__c.field-meta.xml
<CustomField>
    <fullName>Quest_City__c</fullName>
    <description>The city affiliated with this quest.</description>
    <label>Quest City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quest__c/fields/Quest_Country__c.field-meta.xml
<CustomField>
    <fullName>Quest_Country__c</fullName>
    <description>The country affiliated with this quest.</description>
    <label>Quest Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quest__c/fields/Quest_Details__c.field-meta.xml
<CustomField>
    <fullName>Quest_Details__c</fullName>
    <label>Quest Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Quest_Postal_Code__c</fullName>
    <description>The postal code of the quest-giver.</description>
    <label>Quest Postal Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_State__c.field-meta.xml
<CustomField>
    <fullName>Quest_State__c</fullName>
    <description>The home state of the quest-giver.</description>
    <label>Quest State</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_Street__c.field-meta.xml
<CustomField>
    <fullName>Quest_Street__c</fullName>
    <description>The street address of the quest-giver.</description>
    <label>Quest Street</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Required_Professions__c.field-meta.xml
<CustomField>
    <fullName>Required_Professions__c</fullName>
    <label>Required Professions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventurer</fullName>
            </value>
            <value>
                <fullName>Craftsman</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Requires_Party__c.field-meta.xml
<CustomField>
    <fullName>Requires_Party__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Party</label>
    <type>Checkbox</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <description>The sub-status of a quest&apos;s completion.</description>
    <label>Sub-Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Never</fullName>
            </value>
            <value>
                <fullName>Gonna</fullName>
            </value>
            <value>
                <fullName>Give</fullName>
            </value>
            <value>
                <fullName>You</fullName>
            </value>
            <value>
                <fullName>Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/classes/TestQuestPage.cls
@isTest
public class TestQuestPage {
	@testSetup
    public static void setup() {
        Contact con = new Contact();
        con.LastName = 'Flay';
        con.Email = 'dummy@contact.com';
        insert con;
        
        Guild_Member__c guildMem = new Guild_Member__c();
        guildMem.Name = 'Steve';
        guildMem.Member_Email__c = 'dummy@guildMember.com';
        guildMem.Artificer_Level__c = 1;
        insert guildMem;
    }
    
    // positive single test
    @isTest
    public static void testSingleCreateQuest01() {
        Contact con = [SELECT LastName, Email FROM Contact WHERE Email = 'dummy@contact.com'];
        Quest__c q = new Quest__c();
        q.Contact__c = con.Id;
        
        q.Name = 'Kill the Chicken!';
        q.Danger_Level__c = 'Easy';
        q.Location__c = 'Runescape';
        q.Requires_Party__c = true;
        q.Quest_Details__c = 'There\'s a chicken ravaging Edgeville!';
        q.Reward__c = 800;
        q.Required_Professions__c = 'Adventurer;Craftsman';
        
        // standard stuff
        q.Status__c = 'New';
        q.Sub_Status__c = 'Pending';
        q.Date_Opened__c = Date.today();
        
        // deprecated, but needed for now
        q.Quest_Country__c = 'USA';
        q.Quest_City__c = 'Baltimore';
        q.Quest_Postal_Code__c = '20740';
        q.Quest_Street__c = '123 main ave';
        q.Quest_State__c = 'Maryland';
        
        Database.SaveResult sr = Database.insert(q, false);
       	System.assert(sr.isSuccess());
    }
    
    // negative single test
    @isTest
    public static void testSingleCreateQuest02() {
        Quest__c q = new Quest__c();
        q.Contact__c = null;
        
        q.Name = 'Kill the Chicken!';
        q.Danger_Level__c = 'Easy';
        q.Location__c = 'Runescape';
        q.Requires_Party__c = true;
        q.Quest_Details__c = 'There\'s a chicken ravaging Edgeville!';
        q.Reward__c = 800;
        q.Required_Professions__c = 'Adventurer;Craftsman';
        
        
        
        // standard stuff
        q.Status__c = 'New';
        q.Sub_Status__c = 'Pending';
        q.Date_Opened__c = Date.today();
        
        // deprecated, but needed for now
        q.Quest_Country__c = 'USA';
        q.Quest_City__c = 'Baltimore';
        q.Quest_Postal_Code__c = '20740';
        q.Quest_Street__c = '123 main ave';
        q.Quest_State__c = 'Maryland';
        
        Database.SaveResult sr = Database.insert(q, false);
       	System.assert(!sr.isSuccess());
    }
    
    // positive bulk test
    @isTest
    public static void testMassCreateQuest01() {
        List<Quest__c> questList = new List<Quest__c>();
        Contact con = [SELECT LastName, Email FROM Contact WHERE Email = 'dummy@contact.com'];
        for(Integer i = 0; i < 50; i++) {
            Quest__c q = new Quest__c();
            q.Contact__c = con.Id;
            
            q.Name = 'Kill the Chicken!';
            q.Danger_Level__c = 'Easy';
            q.Location__c = 'Runescape';
            q.Requires_Party__c = true;
            q.Quest_Details__c = 'There\'s a chicken ravaging Edgeville!';
            q.Reward__c = 800;
            q.Required_Professions__c = 'Adventurer;Craftsman';
        
        
        
            // standard stuff
            q.Status__c = 'New';
            q.Sub_Status__c = 'Pending';
            q.Date_Opened__c = Date.today();
            
            // deprecated, but needed for now
            q.Quest_Country__c = 'USA';
            q.Quest_City__c = 'Baltimore';
            q.Quest_Postal_Code__c = '20740';
            q.Quest_Street__c = '123 main ave';
            q.Quest_State__c = 'Maryland';
            
            questList.add(q);
        }
        List<Database.SaveResult> srList = Database.insert(questList, false);
        for(Database.SaveResult sr: srList) {
        	System.assert(sr.isSuccess());
        }
    }
    
    // negative bulk test
    @isTest
    public static void testMassCreateQuest02() {
        List<Quest__c> questList = new List<Quest__c>();

        for(Integer i = 0; i < 50; i++) {
            Quest__c q = new Quest__c();
            
            // most likely mistake -- an email with no contact
            q.Contact__c = null;
            
            q.Name = 'Kill the Chicken!';
            q.Danger_Level__c = 'Easy';
            q.Location__c = 'Runescape';
            q.Requires_Party__c = true;
            q.Quest_Details__c = 'There\'s a chicken ravaging Edgeville!';
            q.Reward__c = 800;
            q.Required_Professions__c = 'Adventurer;Craftsman';
        
        
        
            // standard stuff
            q.Status__c = 'New';
            q.Sub_Status__c = 'Pending';
            q.Date_Opened__c = Date.today();
            
            // deprecated, but needed for now
            q.Quest_Country__c = 'USA';
            q.Quest_City__c = 'Baltimore';
            q.Quest_Postal_Code__c = '20740';
            q.Quest_Street__c = '123 main ave';
            q.Quest_State__c = 'Maryland';
            
            questList.add(q);
        }
        List<Database.SaveResult> srList = Database.insert(questList, false);
        for(Database.SaveResult sr: srList) {
        	System.assert(!sr.isSuccess());
        }
    }
    
    // save quest positive single test
    @isTest
    public static void testQuestExt01() {
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Quest__c>());
        QuestExtension ext = new QuestExtension(ssc);
        
        final String dummyContactEmail = 'dummy@contact.com';
        
        ext.formData.questName = 'Kill the Chicken!';
        ext.formData.questDetails = 'There\'s a chicken ravaging Edgeville!';
        ext.formData.location = 'Runescape';
        ext.formData.requiresParty = false;
        ext.formData.dangerLevel = 'Easy';
        ext.formData.requiredProfessionAdventurer = false;
        ext.formData.requiredProfessionCraftsman = true;
        ext.formData.reward = 500;
        ext.formData.email = dummyContactEmail;
        
            
        System.assertNotEqualS(ext.saveQuest(), null);
    }
    
    // save quest negative single test
    @isTest
    public static void testQuestExt02() {
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Quest__c>());
        QuestExtension ext = new QuestExtension(ssc);
        
        final String dummyEmail = 'dummy1@contact.com';
        
        ext.formData.questName = 'Kill the Chicken!';
        ext.formData.questDetails = 'There\'s a chicken ravaging Edgeville!';
        ext.formData.location = 'Runescape';
        ext.formData.requiresParty = true;
        ext.formData.dangerLevel = 'Easy';
        ext.formData.requiredProfessionAdventurer = true;
        ext.formData.requiredProfessionCraftsman = false;
        ext.formData.reward = 500;
        ext.formData.email = dummyEmail;
        
            
        System.assertNotEqualS(ext.saveQuest(), Page.QuestPageSuccessfulSubmission);
    }
    
    // save quest positive bulk test
    @isTest
    public static void testQuestExt03() {
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Quest__c>());
        QuestExtension ext = new QuestExtension(ssc);
        
        for(Integer i = 0; i < 50; i++) {
            final String dummyEmail = 'dummy@contact.com';
            
            ext.formData.questName = 'Kill the Chicken!';
            ext.formData.questDetails = 'There\'s a chicken ravaging Edgeville!';
            ext.formData.location = 'Runescape';
            ext.formData.requiresParty = false;
            ext.formData.dangerLevel = 'Easy';
            ext.formData.requiredProfessionAdventurer = false;
            ext.formData.requiredProfessionCraftsman = true;
            ext.formData.reward = 500;
            ext.formData.email = dummyEmail;
            
                
            System.assertNotEqualS(ext.saveQuest(), null);
        }
    }
    
    // save quest negative bulk test
    @isTest
    public static void testQuestExt04() {
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Quest__c>());
        QuestExtension ext = new QuestExtension(ssc);
        
        for(Integer i = 0; i < 50; i++) {
            final String dummyEmail = 'dummy1@contact.com';
            
            ext.formData.questName = 'Kill the Chicken!';
            ext.formData.questDetails = 'There\'s a chicken ravaging Edgeville!';
            ext.formData.location = 'Runescape';
            ext.formData.requiresParty = true;
            ext.formData.dangerLevel = 'Easy';
            ext.formData.requiredProfessionAdventurer = true;
            ext.formData.requiredProfessionCraftsman = false;
            ext.formData.reward = 500;
            ext.formData.email = dummyEmail;
            
                
            System.assertNotEqualS(ext.saveQuest(), Page.QuestPageSuccessfulSubmission);
        }
    }
    
    // test extension basic getters
    @isTest
    public static void testQuestExt05() {
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Quest__c>());
        QuestExtension ext = new QuestExtension(ssc);
        
        // ensure it succeeds when it should
        System.assertEquals(ext.getDescription(), 'Select a quest from the left to see its information here');
        System.assertEquals(ext.getTitle(), 'Quest Panel');
        ext.questId = '1';
        
        // ensure it succeeds when id is invalid
        System.assertEquals(ext.getDescription(), 'Select a quest from the left to see its information here');
        System.assertEquals(ext.getTitle(), 'Quest Panel');
        
        // ensure it succeeds when it should
        final String dummyEmail = 'dummy@contact.com';
        
        ext.formData.questName = 'Kill the Chicken!';
        ext.formData.questDetails = 'There is a chicken ravaging Edgeville!';
        ext.formData.location = 'Runescape';
        ext.formData.requiresParty = true;
        ext.formData.dangerLevel = 'Easy';
        ext.formData.requiredProfessionAdventurer = true;
        ext.formData.requiredProfessionCraftsman = false;
        ext.formData.reward = 500;
        ext.formData.email = dummyEmail;
        
        ext.saveQuest();
        
        Quest__c q = [SELECT Id FROM Quest__c WHERE Contact__r.Email = :dummyEmail];
        ext.questId = q.id;
        System.assertEquals(ext.getDescription(), 'There is a chicken ravaging Edgeville!');
        System.assertEquals(ext.getTitle(), 'Kill the Chicken!');
    }
    
    // test extension submit for approval single positive
    @isTest
    public static void testQuestExt06() {
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Quest__c>());
        QuestExtension ext = new QuestExtension(ssc);
        System.assertEquals(ext.submitForApproval(), null);
        
        final String dummyContactEmail = 'dummy@contact.com';
        final String dummyGuildMemberEmail = 'dummy@guildmember.com';
        final String questName = 'Kill the Chicken!';
        
        ext.formData.questName = questName;
        ext.formData.questDetails = 'There is a chicken ravaging Edgeville!';
        ext.formData.location = 'Runescape';
        ext.formData.requiresParty = true;
        ext.formData.dangerLevel = 'Easy';
        ext.formData.requiredProfessionAdventurer = true;
        ext.formData.requiredProfessionCraftsman = true;
        ext.formData.reward = 500;
        ext.formData.email = dummyContactEmail;
        
        System.assertNotEquals(ext.saveQuest(), null);
        Quest__c q = [SELECT Id FROM Quest__c WHERE Name = :questName];
        ext.assigneeEmail = dummyGuildMemberEmail;
        System.assertEquals(ext.submitForApproval(), null);
        
        ext.questId = q.Id;
        System.assertNotEquals(ext.submitForApproval(), null);
    }
    
    // test extension submit for approval single negative
    @isTest
    public static void testQuestExt07() {
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Quest__c>());
        QuestExtension ext = new QuestExtension(ssc);
        System.assertEquals(ext.submitForApproval(), null);
        
        final String dummyContactEmail = 'dummy@contact.com';
        final String dummyGuildMemEmail = 'dummy1@guildMember.com';
        final String questName = 'Kill the Chicken!';
        
        ext.formData.questName = questName;
        ext.formData.questDetails = 'There is a chicken ravaging Edgeville!';
        ext.formData.location = 'Runescape';
        ext.formData.requiresParty = true;
        ext.formData.dangerLevel = 'Easy';
        ext.formData.requiredProfessionAdventurer = true;
        ext.formData.requiredProfessionCraftsman = true;
        ext.formData.reward = 500;
        ext.formData.email = dummyContactEmail;
        
        System.assertNotEquals(ext.saveQuest(), null);
        Quest__c q = [SELECT Id FROM Quest__c WHERE Name = :questName];
        
        // email that DNE
        ext.assigneeEmail = dummyGuildMemEmail;
        System.assertEquals(ext.submitForApproval(), null);
        
        ext.questId = q.Id;
        System.assertEquals(ext.submitForApproval(), null);
    }
    
    // test contact trigger handler negative test concurrent add
    @isTest
    public static void testContactTriggerHandler01() {
        Contact c0 = new Contact(LastName = 'Bob', Email='bob@bob.com');
        Contact c1 = new Contact(LastName= 'bob', Email='bob@bob.com');
        List<Contact> conList = new List<Contact>{c0, c1};
        try {
            insert conList;
            System.assert(false);
        } catch(exception e) {
            System.assert(true);
        }
    }
    
    // test contact trigger handler positive test concurrent add
    @isTest
    public static void testContactTriggerHandler02() {
        Contact c0 = new Contact(LastName = 'Bob', Email='bob@bob.com');
        Contact c1 = new Contact(LastName= 'bob', Email='bob2@bob.com');
        List<Contact> conList = new List<Contact>{c0, c1};
        try {
            insert conList;
            System.assert(true);
        } catch(exception e) {
            System.assert(false);
        }
    }
    
    // test contact trigger handler negative test single add
    @isTest
    public static void testContactTriggerHandler03() {
        Contact c0 = new Contact(LastName = 'Bob', Email='bob@bob.com');
        Contact c1 = new Contact(LastName= 'bob', Email='bob@bob.com');
        
        try {
            insert c0;
        } catch(Exception e) {
            System.assert(false);
        }
        
        try {
            insert c1;
        } catch(Exception e) {
            System.assert(true);
        }
    }
    
    // test contact trigger handler positive test single add
    @isTest
    public static void testContactTriggerHandler04() {
        Contact c0 = new Contact(LastName = 'Bob', Email='bob@bob.com');
        Contact c1 = new Contact(LastName= 'bob', Email='bob2@bob.com');
        try {
            insert c0;
            insert c1;
            System.assert(true);
        } catch(Exception e) {
            System.assert(false);
        }
    }
}