Project1/force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>The guild member excels at these things.</description>
    <inlineHelpText>What does this guild member excel at?</inlineHelpText>
    <label>Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skills</valueSetName>
    </valueSet>
</CustomField>

Project1/force-app/main/default/globalValueSets/Skills.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Athletics</fullName>
    </customValue>
    <customValue>
        <fullName>Acrobatics</fullName>
    </customValue>
    <customValue>
        <fullName>Sleight of Hand</fullName>
    </customValue>
    <customValue>
        <fullName>Stealth</fullName>
    </customValue>
    <customValue>
        <fullName>Arcana</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Investigation</fullName>
    </customValue>
    <customValue>
        <fullName>Nature</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Handling</fullName>
    </customValue>
    <customValue>
        <fullName>Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Perception</fullName>
    </customValue>
    <customValue>
        <fullName>Survival</fullName>
    </customValue>
    <customValue>
        <fullName>Deception</fullName>
    </customValue>
    <customValue>
        <fullName>Intimidation</fullName>
    </customValue>
    <customValue>
        <fullName>Performance</fullName>
    </customValue>
    <customValue>
        <fullName>Persuasion</fullName>
    </customValue>
    <customValue>
        <fullName>Alchemy</fullName>
    </customValue>
    <customValue>
        <fullName>Brewing</fullName>
    </customValue>
    <customValue>
        <fullName>Calligraphy</fullName>
    </customValue>
    <customValue>
        <fullName>Carpentry</fullName>
    </customValue>
    <customValue>
        <fullName>Cartography</fullName>
    </customValue>
    <customValue>
        <fullName>Cobbling</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Glassblowing</fullName>
    </customValue>
    <customValue>
        <fullName>Jeweling</fullName>
    </customValue>
    <customValue>
        <fullName>Leatherworking</fullName>
    </customValue>
    <customValue>
        <fullName>Masonry</fullName>
    </customValue>
    <customValue>
        <fullName>Painting</fullName>
    </customValue>
    <customValue>
        <fullName>Pottery</fullName>
    </customValue>
    <masterLabel>Skills</masterLabel>
</GlobalValueSet>

Project1/force-app/main/default/classes/GuildMemberExtension.cls
public class GuildMemberExtension {
    
    public GuildMemberExtension(ApexPages.StandardSetController ssc){
        ssc.setPageSize(10);
    }
    
    public List<SelectOption> getSkills() {
        List<SelectOption> skills = new List<SelectOption>();
        Schema.DescribeFieldResult describeResult = Guild_Member__c.Skills__c.getDescribe();
        List<Schema.PicklistEntry> picklistEntries = describeResult.getPickListValues();
        for(Schema.PicklistEntry pe : picklistEntries){
            skills.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        return skills;
    }
    
}