Project1/force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Artificer</fullName>
            </value>
            <value>
                <fullName>Barbarian</fullName>
            </value>
            <value>
                <fullName>Bard</fullName>
            </value>
            <value>
                <fullName>Cleric</fullName>
            </value>
            <value>
                <fullName>Druid</fullName>
            </value>
            <value>
                <fullName>Fighter</fullName>
            </value>
            <value>
                <fullName>Monk</fullName>
            </value>
            <value>
                <fullName>Paladin</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
            <value>
                <fullName>Rogue</fullName>
            </value>
            <value>
                <fullName>Sorcerer</fullName>
            </value>
            <value>
                <fullName>Warlock</fullName>
            </value>
            <value>
                <fullName>Wizard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/Member_Assignment__c.object-meta.xml
<CustomObject>
    <label>Member Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Member Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Party__c/fields/Class_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Class_Requirements__c</fullName>
    <description>All selected classes are the required class to apply to join the party.</description>
    <label>Class Requirements</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

Project1/force-app/main/default/globalValueSets/Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Artificer</fullName>
    </customValue>
    <customValue>
        <fullName>Barbarian</fullName>
    </customValue>
    <customValue>
        <fullName>Bard</fullName>
    </customValue>
    <customValue>
        <fullName>Cleric</fullName>
    </customValue>
    <customValue>
        <fullName>Druid</fullName>
    </customValue>
    <customValue>
        <fullName>Fighter</fullName>
    </customValue>
    <customValue>
        <fullName>Monk</fullName>
    </customValue>
    <customValue>
        <fullName>Paladin</fullName>
    </customValue>
    <customValue>
        <fullName>Ranger</fullName>
    </customValue>
    <customValue>
        <fullName>Rogue</fullName>
    </customValue>
    <customValue>
        <fullName>Sorcerer</fullName>
    </customValue>
    <customValue>
        <fullName>Warlock</fullName>
    </customValue>
    <customValue>
        <fullName>Wizard</fullName>
    </customValue>
    <description>List of all adventurer classes.</description>
    <masterLabel>Class</masterLabel>
</GlobalValueSet>

Project1/force-app/main/default/classes/MemberAssignmentTriggerHandler.cls
public class MemberAssignmentTriggerHandler {
    
    public static void validateClass(List<Member_Assignment__c> assignments) {
        for (Member_Assignment__c ma : assignments) {
            List<string> partyClasses = [SELECT class_requirements__c FROM Party__c WHERE id = :ma.party__c LIMIT 1].class_requirements__c.split(';');
            List<string> memberClasses = [SELECT class__c FROM Guild_Member__c WHERE id = :ma.guild_member__c LIMIT 1].class__c.split(';');
            boolean match = false;
            for (string partyClass : partyClasses) {
                for (string memberClass : memberClasses) {
                    if (partyClass == memberClass) {
                        match = true;
                    }
                }
            }
            if (!match) {
                ma.addError('The member does not have any of the party required classes.');
            }
        }
    }

}