Project1/force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Artificer_Level__c.field-meta.xml
<CustomField>
    <fullName>Artificer_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Artificer Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Artificer</fullName>
            </value>
            <value>
                <fullName>Barbarian</fullName>
            </value>
            <value>
                <fullName>Bard</fullName>
            </value>
            <value>
                <fullName>Cleric</fullName>
            </value>
            <value>
                <fullName>Druid</fullName>
            </value>
            <value>
                <fullName>Fighter</fullName>
            </value>
            <value>
                <fullName>Monk</fullName>
            </value>
            <value>
                <fullName>Paladin</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
            <value>
                <fullName>Rogue</fullName>
            </value>
            <value>
                <fullName>Sorcerer</fullName>
            </value>
            <value>
                <fullName>Warlock</fullName>
            </value>
            <value>
                <fullName>Wizard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Member_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Member Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Guild_Member_Record</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/Member_Assignment__c.object-meta.xml
<CustomObject>
    <label>Member Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Member Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Party__c/fields/Accepting_New_Members__c.field-meta.xml
<CustomField>
    <fullName>Accepting_New_Members__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if the party is accepting new members.</description>
    <label>Accepting New Members</label>
    <type>Checkbox</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Class_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Class_Requirements__c</fullName>
    <description>All selected classes are the required class to apply to join the party.</description>
    <label>Class Requirements</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Max_Party_Size__c.field-meta.xml
<CustomField>
    <fullName>Max_Party_Size__c</fullName>
    <description>The maximum number of members allowed in this party. Set by the party owner.</description>
    <label>Max Party Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Minimum_Level_Required__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Level_Required__c</fullName>
    <description>The minimum level required by the party leader for accepting new members.</description>
    <label>Minimum Level Required</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Party_Size__c.field-meta.xml
<CustomField>
    <fullName>Party_Size__c</fullName>
    <description>The current number of members in the party.</description>
    <label>Party Size</label>
    <summaryForeignKey>Member_Assignment__c.Party__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Project1/force-app/main/default/globalValueSets/Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Artificer</fullName>
    </customValue>
    <customValue>
        <fullName>Barbarian</fullName>
    </customValue>
    <customValue>
        <fullName>Bard</fullName>
    </customValue>
    <customValue>
        <fullName>Cleric</fullName>
    </customValue>
    <customValue>
        <fullName>Druid</fullName>
    </customValue>
    <customValue>
        <fullName>Fighter</fullName>
    </customValue>
    <customValue>
        <fullName>Monk</fullName>
    </customValue>
    <customValue>
        <fullName>Paladin</fullName>
    </customValue>
    <customValue>
        <fullName>Ranger</fullName>
    </customValue>
    <customValue>
        <fullName>Rogue</fullName>
    </customValue>
    <customValue>
        <fullName>Sorcerer</fullName>
    </customValue>
    <customValue>
        <fullName>Warlock</fullName>
    </customValue>
    <customValue>
        <fullName>Wizard</fullName>
    </customValue>
    <description>List of all adventurer classes.</description>
    <masterLabel>Class</masterLabel>
</GlobalValueSet>

Project1/force-app/main/default/classes/PartyListPageControllerTest.cls
@isTest
public class PartyListPageControllerTest {
    
    private static string partyid;
    
    private static void singleSetup() {
        Party__c testParty = new Party__c();
        testParty.Name = 'test';
        testParty.Accepting_New_Members__c = true;
        testParty.Max_Party_Size__c = 4;
        testParty.Minimum_Level_Required__c = 5;
        testParty.Class_Requirements__c = 'Cleric;Fighter';
        insert testParty;
        Guild_Member__c testMember = new Guild_Member__c();
        testMember.Name = 'bob';
        testMember.Member_Email__c = 'bob@bob.bob';
        testMember.class__c = 'Fighter';
        testMember.Artificer_Level__c = 1;
        insert testMember;
        testParty = [SELECT id FROM Party__c LIMIT 1];
        partyid = testParty.id;
        testMember = [SELECT id FROM Guild_Member__c LIMIT 1];
        Member_Assignment__c ma = new Member_Assignment__c();
        ma.Guild_Member__c = testMember.id;
        ma.Party__c = testParty.id;
        insert ma;
    }

    @isTest
    public static void testGetPartiesName() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByName = 'es';
        List<Party__c> parties = plpc.getParties();
        for (Party__c p : parties) {
            system.assertEquals(p.Name, 'test');
        }
    }
    
    @isTest
    public static void testGetPartiesNameNegative() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByName = 'bob';
        List<Party__c> parties = plpc.getParties();
        system.assert(parties.isEmpty());
    }
    
    @isTest
    public static void testGetPartiesAccept() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByAcceptingNewMembers = 'true';
        List<Party__c> parties = plpc.getParties();
        for (Party__c p : parties) {
            system.assertEquals(p.Name, 'test');
        }
    }
    
    @isTest
    public static void testGetPartiesAcceptNegative() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByAcceptingNewMembers = 'false';
        List<Party__c> parties = plpc.getParties();
        system.assert(parties.isEmpty());
    }
    
    @isTest
    public static void testGetPartiesSize() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByPartySize = 1;
        plpc.filterByPartySizeComparisonOp = '=';
        List<Party__c> parties = plpc.getParties();
        for (Party__c p : parties) {
            system.assertEquals(p.Name, 'test');
            system.assertEquals(1, p.Party_Size__c);
        }
    }
    
    @isTest
    public static void testGetPartiesSizeNegative() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByPartySize = 1;
        plpc.filterByPartySizeComparisonOp = '>';
        List<Party__c> parties = plpc.getParties();
        system.assert(parties.isEmpty());
    }
    
    @isTest
    public static void testGetPartiesMaxSize() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByMaxPartySize = 4;
        plpc.filterByMaxPartySizeComparisonOp = '=';
        List<Party__c> parties = plpc.getParties();
        for (Party__c p : parties) {
            system.assertEquals(p.Name, 'test');
        }
    }
    
    @isTest
    public static void testGetPartiesMaxSizeNegative() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByMaxPartySize = 4;
        plpc.filterByMaxPartySizeComparisonOp = '<';
        List<Party__c> parties = plpc.getParties();
        system.assert(parties.isEmpty());
    }
    
    @isTest
    public static void testGetPartiesMinLvl() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByMinimumLevelRequired = 5;
        plpc.filterByMinLvlReqComparisonOp = '=';
        List<Party__c> parties = plpc.getParties();
        for (Party__c p : parties) {
            system.assertEquals(p.Name, 'test');
        }
    }
    
    @isTest
    public static void testGetPartiesMinLvlNegative() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByMinimumLevelRequired = 5;
        plpc.filterByMinLvlReqComparisonOp = '>';
        List<Party__c> parties = plpc.getParties();
        system.assert(parties.isEmpty());
    }
    
    @isTest
    public static void testGetPartiesClass() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByClassRequirements = new List<string>();
        plpc.filterByClassRequirements.add('Fighter');
        List<Party__c> parties = plpc.getParties();
        for (Party__c p : parties) {
            system.assertEquals(p.Name, 'test');
        }
    }
    
    @isTest
    public static void testGetPartiesClassNegative() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByClassRequirements = new List<string>();
        plpc.filterByClassRequirements.add('Warlock');
        plpc.filterByClassRequirements.add('Wizard');
        List<Party__c> parties = plpc.getParties();
        system.assert(parties.isEmpty());
    }
    
    @isTest
    public static void testGetPartiesManyFilters() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.filterByName = 'es';
        plpc.filterByAcceptingNewMembers = 'true';
        plpc.filterByPartySize = 1;
        plpc.filterByPartySizeComparisonOp = '=';
        plpc.filterByMaxPartySize = 4;
        plpc.filterByMaxPartySizeComparisonOp = '=';
        plpc.filterByMinimumLevelRequired = 5;
        plpc.filterByMinLvlReqComparisonOp = '=';
        plpc.filterByClassRequirements = new List<string>();
        plpc.filterByClassRequirements.add('Fighter');
        List<Party__c> parties = plpc.getParties();
        for (Party__c p : parties) {
            system.assertEquals(p.Name, 'test');
        }
    }
    
    @isTest
    public static void testJoinParty() {
        singleSetup();
        PartyListPageController plpc = new PartyListPageController();
        plpc.partyid = partyid;
        plpc.currentParty = [SELECT id FROM Party__c WHERE id = :partyid];
        Guild_Member__c gm = new Guild_Member__c();
        gm.User__c = UserInfo.getUserId();
        gm.Name = 'Tom';
        gm.Member_Email__c = 'tom@tom.tom';
        gm.class__c = 'Cleric';
        gm.Artificer_Level__c = 1;
        insert gm;
        plpc.joinParty();
        Party__c party = [SELECT Party_Size__c, (SELECT Guild_Member__c FROM Member_Assignments__r) FROM Party__c LIMIT 1];
        system.assertEquals(2, party.Member_Assignments__r.size());
        system.assertEquals(party.Party_Size__c, 2);
        List<string> memberids = new List<string>();
        for (Member_Assignment__c ma : party.Member_Assignments__r) {
            memberids.add(ma.Guild_Member__c);
        }
        List<Guild_Member__c> members = [SELECT Name FROM Guild_Member__c WHERE id IN :memberids];
        Set<string> names = new Set<string>();
        for (Guild_Member__c member : members) {
            names.add(member.Name);
        }
        system.assert(names.contains('Tom'));
    }
    
}