Project1/force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Artificer_Level__c.field-meta.xml
<CustomField>
    <fullName>Artificer_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Artificer Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Barbarian_Level__c.field-meta.xml
<CustomField>
    <fullName>Barbarian_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Barbarian Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Bard_Level__c.field-meta.xml
<CustomField>
    <fullName>Bard_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bard Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Artificer</fullName>
            </value>
            <value>
                <fullName>Barbarian</fullName>
            </value>
            <value>
                <fullName>Bard</fullName>
            </value>
            <value>
                <fullName>Cleric</fullName>
            </value>
            <value>
                <fullName>Druid</fullName>
            </value>
            <value>
                <fullName>Fighter</fullName>
            </value>
            <value>
                <fullName>Monk</fullName>
            </value>
            <value>
                <fullName>Paladin</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
            <value>
                <fullName>Rogue</fullName>
            </value>
            <value>
                <fullName>Sorcerer</fullName>
            </value>
            <value>
                <fullName>Warlock</fullName>
            </value>
            <value>
                <fullName>Wizard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Cleric_Level__c.field-meta.xml
<CustomField>
    <fullName>Cleric_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cleric Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guild_Member__c/fields/Date_Hired__c.field-meta.xml
<CustomField>
    <fullName>Date_Hired__c</fullName>
    <label>Date Hired</label>
    <type>Date</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Druid_Level__c.field-meta.xml
<CustomField>
    <fullName>Druid_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Druid Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Fighter_Level__c.field-meta.xml
<CustomField>
    <fullName>Fighter_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fighter Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Guild_Hall__c.field-meta.xml
<CustomField>
    <fullName>Guild_Hall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Hall</label>
    <referenceTo>Guild_Hall__c</referenceTo>
    <relationshipLabel>Guild Members</relationshipLabel>
    <relationshipName>Guild_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Monk_Level__c.field-meta.xml
<CustomField>
    <fullName>Monk_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monk Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Paladin_Level__c.field-meta.xml
<CustomField>
    <fullName>Paladin_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Paladin Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aarakocra</fullName>
            </value>
            <value>
                <fullName>Aasimar</fullName>
            </value>
            <value>
                <fullName>Bugbear</fullName>
            </value>
            <value>
                <fullName>Centuar</fullName>
            </value>
            <value>
                <fullName>Changeling</fullName>
            </value>
            <value>
                <fullName>Dragonborn</fullName>
            </value>
            <value>
                <fullName>Dwarf</fullName>
            </value>
            <value>
                <fullName>Elf</fullName>
            </value>
            <value>
                <fullName>Firbolg</fullName>
            </value>
            <value>
                <fullName>Genasi</fullName>
            </value>
            <value>
                <fullName>Gith</fullName>
            </value>
            <value>
                <fullName>Gnome</fullName>
            </value>
            <value>
                <fullName>Goblin</fullName>
            </value>
            <value>
                <fullName>Goliath</fullName>
            </value>
            <value>
                <fullName>Half-Elf</fullName>
            </value>
            <value>
                <fullName>Halfling</fullName>
            </value>
            <value>
                <fullName>Half-Orc</fullName>
            </value>
            <value>
                <fullName>Hobgoblin</fullName>
            </value>
            <value>
                <fullName>Human</fullName>
            </value>
            <value>
                <fullName>Kalashtar</fullName>
            </value>
            <value>
                <fullName>Kenku</fullName>
            </value>
            <value>
                <fullName>Kobold</fullName>
            </value>
            <value>
                <fullName>Lizardfolk</fullName>
            </value>
            <value>
                <fullName>Loxodon</fullName>
            </value>
            <value>
                <fullName>Minotaur</fullName>
            </value>
            <value>
                <fullName>Orc</fullName>
            </value>
            <value>
                <fullName>Shifter</fullName>
            </value>
            <value>
                <fullName>Simic Hybrid</fullName>
            </value>
            <value>
                <fullName>Tabaxi</fullName>
            </value>
            <value>
                <fullName>Tiefling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Ranger_Level__c.field-meta.xml
<CustomField>
    <fullName>Ranger_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ranger Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Rogue_Level__c.field-meta.xml
<CustomField>
    <fullName>Rogue_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rogue Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>The guild member excels at these things.</description>
    <inlineHelpText>What does this guild member excel at?</inlineHelpText>
    <label>Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skills</valueSetName>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Sorcerer_Level__c.field-meta.xml
<CustomField>
    <fullName>Sorcerer_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sorcerer Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Total_Level__c.field-meta.xml
<CustomField>
    <fullName>Total_Level__c</fullName>
    <formula>Artificer_Level__c +  Barbarian_Level__c + Bard_Level__c + Cleric_Level__c + Druid_Level__c + Fighter_Level__c + Monk_Level__c + Paladin_Level__c + Ranger_Level__c + Rogue_Level__c + Sorcerer_Level__c + Warlock_Level__c + Wizard_Level__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Guild_Member_Record</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Warlock_Level__c.field-meta.xml
<CustomField>
    <fullName>Warlock_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Warlock Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Wizard_Level__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wizard Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Guild_Hall__c.field-meta.xml
<CustomField>
    <fullName>Guild_Hall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Hall</label>
    <referenceTo>Guild_Hall__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Item__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/Member_Assignment__c.object-meta.xml
<CustomObject>
    <label>Member Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Member Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/Quest__c.object-meta.xml
<CustomObject>
    <label>Quest</label>
    <nameField>
        <label>Quest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Quest__c/fields/Guild_Hall__c.field-meta.xml
<CustomField>
    <fullName>Guild_Hall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Hall</label>
    <referenceTo>Guild_Hall__c</referenceTo>
    <relationshipLabel>Quests</relationshipLabel>
    <relationshipName>Quests</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Quests</relationshipLabel>
    <relationshipName>Quests</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Quests</relationshipLabel>
    <relationshipName>Quests</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/globalValueSets/Skills.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Athletics</fullName>
    </customValue>
    <customValue>
        <fullName>Acrobatics</fullName>
    </customValue>
    <customValue>
        <fullName>Sleight of Hand</fullName>
    </customValue>
    <customValue>
        <fullName>Stealth</fullName>
    </customValue>
    <customValue>
        <fullName>Arcana</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Investigation</fullName>
    </customValue>
    <customValue>
        <fullName>Nature</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Handling</fullName>
    </customValue>
    <customValue>
        <fullName>Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Perception</fullName>
    </customValue>
    <customValue>
        <fullName>Survival</fullName>
    </customValue>
    <customValue>
        <fullName>Deception</fullName>
    </customValue>
    <customValue>
        <fullName>Intimidation</fullName>
    </customValue>
    <customValue>
        <fullName>Performance</fullName>
    </customValue>
    <customValue>
        <fullName>Persuasion</fullName>
    </customValue>
    <customValue>
        <fullName>Alchemy</fullName>
    </customValue>
    <customValue>
        <fullName>Brewing</fullName>
    </customValue>
    <customValue>
        <fullName>Calligraphy</fullName>
    </customValue>
    <customValue>
        <fullName>Carpentry</fullName>
    </customValue>
    <customValue>
        <fullName>Cartography</fullName>
    </customValue>
    <customValue>
        <fullName>Cobbling</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Glassblowing</fullName>
    </customValue>
    <customValue>
        <fullName>Jeweling</fullName>
    </customValue>
    <customValue>
        <fullName>Leatherworking</fullName>
    </customValue>
    <customValue>
        <fullName>Masonry</fullName>
    </customValue>
    <customValue>
        <fullName>Painting</fullName>
    </customValue>
    <customValue>
        <fullName>Pottery</fullName>
    </customValue>
    <masterLabel>Skills</masterLabel>
</GlobalValueSet>

Project1/force-app/main/default/classes/UserPageController.cls
/* Name: Guild Member Page Controller
 * Author: Blake Prescott
 * Description: This is the page controller for the Guild Member Page/User Page
 * User Page is a misnomer
 */
public with sharing class UserPageController {
    public Guild_Member__c member{get;set;}
    public List<Item__c> items{get;set;}
    public List<Quest__c> quests{get;set;}
    public Member_Assignment__c party{get;set;}
    
    public UserPageController(){
        //if the user navigates to this page from another visualforce page it will get the guild member's id from that page
        //if they don't it will grab the guild member related to the user.
        if(ApexPages.currentPage().getParameters().get('id') != null){
            member = [SELECT Age__c, Class__c, Guild_Hall__c, Name, Race__c, Skills__c, Date_Hired__c,
                      Artificer_Level__c, Barbarian_Level__c, Bard_Level__c, Cleric_Level__c, Druid_Level__c, 
                      Fighter_Level__c, Monk_Level__c, Paladin_Level__c, Ranger_Level__c, Rogue_Level__c, 
                      Sorcerer_Level__c, Warlock_Level__c, Wizard_Level__c, Total_Level__c,
                      (SELECT Item__c.ID FROM Items__r),
                      (SELECT Quest__c.ID FROM Quests__r),
                      (SELECT Member_Assignment__c.ID FROM Member_Assignments__r)
                      FROM Guild_Member__c
                      WHERE Guild_Member__c.ID =: ApexPages.currentPage().getParameters().get('id')
                      LIMIT 1];
        }else{
            member = [SELECT Age__c, Class__c, Guild_Hall__c, Name, Race__c, Skills__c, Date_Hired__c,
                      Artificer_Level__c, Barbarian_Level__c, Bard_Level__c, Cleric_Level__c, Druid_Level__c, 
                      Fighter_Level__c, Monk_Level__c, Paladin_Level__c, Ranger_Level__c, Rogue_Level__c, 
                      Sorcerer_Level__c, Warlock_Level__c, Wizard_Level__c, Total_Level__c,
                      (SELECT Item__c.ID FROM Items__r),
                      (SELECT Quest__c.ID FROM Quests__r),
                      (SELECT Member_Assignment__c.ID FROM Member_Assignments__r)
                      FROM Guild_Member__c
                      WHERE Guild_Member__c.User__r.ID =: UserInfo.getUserId()
                      LIMIT 1];
        }
        
        //Query for the member's items
        items = [SELECT ID, Name, Item_Type__c, Properties__c, Value__c 
                FROM Item__c 
                WHERE ID IN: member.Items__r];
        
        //Query for the member's quests
        quests = [SELECT ID, Name 
                FROM Quest__c 
                WHERE ID IN: member.Quests__r];
        
        //if they have an assignment to a party, it will query for that party's name.
        try{
        	party = [SELECT ID, Party__r.Name
                	FROM Member_Assignment__c
                	WHERE ID IN: member.Member_Assignments__r
                	LIMIT 1];
        }catch(QueryException e){
            party = null;
        }
    }
    
    //updates the record in the database
    public void save(){
        update member;
    }
    

}