Project1/force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Member_Assignment__c/Member_Assignment__c.object-meta.xml
<CustomObject>
    <label>Member Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Member Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Party__c/fields/Accepting_New_Members__c.field-meta.xml
<CustomField>
    <fullName>Accepting_New_Members__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if the party is accepting new members.</description>
    <label>Accepting New Members</label>
    <type>Checkbox</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Class_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Class_Requirements__c</fullName>
    <description>All selected classes are the required class to apply to join the party.</description>
    <label>Class Requirements</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Max_Party_Size__c.field-meta.xml
<CustomField>
    <fullName>Max_Party_Size__c</fullName>
    <description>The maximum number of members allowed in this party. Set by the party owner.</description>
    <label>Max Party Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Minimum_Level_Required__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Level_Required__c</fullName>
    <description>The minimum level required by the party leader for accepting new members.</description>
    <label>Minimum Level Required</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Party_Size__c.field-meta.xml
<CustomField>
    <fullName>Party_Size__c</fullName>
    <description>The current number of members in the party.</description>
    <label>Party Size</label>
    <summaryForeignKey>Member_Assignment__c.Party__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Project1/force-app/main/default/globalValueSets/Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Artificer</fullName>
    </customValue>
    <customValue>
        <fullName>Barbarian</fullName>
    </customValue>
    <customValue>
        <fullName>Bard</fullName>
    </customValue>
    <customValue>
        <fullName>Cleric</fullName>
    </customValue>
    <customValue>
        <fullName>Druid</fullName>
    </customValue>
    <customValue>
        <fullName>Fighter</fullName>
    </customValue>
    <customValue>
        <fullName>Monk</fullName>
    </customValue>
    <customValue>
        <fullName>Paladin</fullName>
    </customValue>
    <customValue>
        <fullName>Ranger</fullName>
    </customValue>
    <customValue>
        <fullName>Rogue</fullName>
    </customValue>
    <customValue>
        <fullName>Sorcerer</fullName>
    </customValue>
    <customValue>
        <fullName>Warlock</fullName>
    </customValue>
    <customValue>
        <fullName>Wizard</fullName>
    </customValue>
    <description>List of all adventurer classes.</description>
    <masterLabel>Class</masterLabel>
</GlobalValueSet>

Project1/force-app/main/default/classes/PartyListPageController.cls
public class PartyListPageController {
    
    private integer numRecords = 0;
    private integer pageIndex = 0;
    public integer pageSize {get;set;}
    private integer offset = 0;
    public boolean filterByAccept {get;set;}
    public string partyid {get;set;}
    public Party__c currentParty {get;set;}
    public List<Guild_Member__c> currentPartyMembers{get;set;}
    public Party__c newParty {get;set;}
    
    public PartyListPageController() {
        numRecords = [SELECT count() FROM Party__c];
		newParty = new Party__c();
		pageSize = 5;        
    }
    
    public List<Party__c> getParties() {
        return [SELECT Name, Party_Size__c, Max_Party_Size__c, Accepting_New_Members__c, Minimum_Level_Required__c, Class_Requirements__c FROM Party__c ORDER BY Name LIMIT :pageSize OFFSET :offset]; 
    }
    
    public void next() {
        pageIndex++;
        offset = pageSize * pageIndex;
    }
    
    public void prev() {
        pageIndex--;
        offset = pageSize * pageIndex;
    }
    
    public void first() {
        pageIndex = 0;
        offset = pageSize * pageIndex;
    }
    
    public void last() {
        if (Math.mod(numRecords, pageSize) == 0) {
            pageIndex = numRecords / pageSize - 1;
            offset = pageSize * pageIndex;
        }
        else {
        	pageIndex = (numRecords - Math.mod(numRecords, pageSize)) / pageSize;
            offset = pageSize * pageIndex;
        }
    }
    
    public boolean getNxt() {
        return (pageIndex+1)*pageSize >= numRecords;
    }
    
    public boolean getPrv() {
        return pageIndex == 0;
    }
    
    public PageReference partyPage() {
        currentParty = [SELECT Name, Party_Size__c, Max_Party_Size__c, Accepting_New_Members__c, Minimum_Level_Required__c, Class_Requirements__c, (SELECT Guild_Member__c FROM Member_Assignments__r) FROM Party__c WHERE id = :partyid];
        Set<string> ids = new Set<string>();
        for (Member_Assignment__c ma : currentParty.Member_Assignments__r) {
            ids.add(ma.Guild_Member__c);
        }
        currentPartyMembers = [SELECT Name FROM Guild_Member__c WHERE id IN :ids];
        return Page.PartyPage;
    }
    
    public void createParty() {
        try {
            insert newParty;
        }
        catch (DMLException e) {
            
        }
        finally {
            newParty = new Party__c();
        }
        
    }

}