Project1/force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Artificer_Level__c.field-meta.xml
<CustomField>
    <fullName>Artificer_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Artificer Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Artificer</fullName>
            </value>
            <value>
                <fullName>Barbarian</fullName>
            </value>
            <value>
                <fullName>Bard</fullName>
            </value>
            <value>
                <fullName>Cleric</fullName>
            </value>
            <value>
                <fullName>Druid</fullName>
            </value>
            <value>
                <fullName>Fighter</fullName>
            </value>
            <value>
                <fullName>Monk</fullName>
            </value>
            <value>
                <fullName>Paladin</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
            <value>
                <fullName>Rogue</fullName>
            </value>
            <value>
                <fullName>Sorcerer</fullName>
            </value>
            <value>
                <fullName>Warlock</fullName>
            </value>
            <value>
                <fullName>Wizard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Member_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Member Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/Member_Assignment__c.object-meta.xml
<CustomObject>
    <label>Member Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Member Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Party__c/fields/Accepting_New_Members__c.field-meta.xml
<CustomField>
    <fullName>Accepting_New_Members__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if the party is accepting new members.</description>
    <label>Accepting New Members</label>
    <type>Checkbox</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Class_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Class_Requirements__c</fullName>
    <description>All selected classes are the required class to apply to join the party.</description>
    <label>Class Requirements</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Party__c/fields/Max_Party_Size__c.field-meta.xml
<CustomField>
    <fullName>Max_Party_Size__c</fullName>
    <description>The maximum number of members allowed in this party. Set by the party owner.</description>
    <label>Max Party Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/globalValueSets/Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Artificer</fullName>
    </customValue>
    <customValue>
        <fullName>Barbarian</fullName>
    </customValue>
    <customValue>
        <fullName>Bard</fullName>
    </customValue>
    <customValue>
        <fullName>Cleric</fullName>
    </customValue>
    <customValue>
        <fullName>Druid</fullName>
    </customValue>
    <customValue>
        <fullName>Fighter</fullName>
    </customValue>
    <customValue>
        <fullName>Monk</fullName>
    </customValue>
    <customValue>
        <fullName>Paladin</fullName>
    </customValue>
    <customValue>
        <fullName>Ranger</fullName>
    </customValue>
    <customValue>
        <fullName>Rogue</fullName>
    </customValue>
    <customValue>
        <fullName>Sorcerer</fullName>
    </customValue>
    <customValue>
        <fullName>Warlock</fullName>
    </customValue>
    <customValue>
        <fullName>Wizard</fullName>
    </customValue>
    <description>List of all adventurer classes.</description>
    <masterLabel>Class</masterLabel>
</GlobalValueSet>

Project1/force-app/main/default/classes/MemberAssignmentTriggerTest.cls
/* 
 * Name: MemberAssignmentTriggerTest
 * Authors: Gregory Mannerberg (gregory.mannerberg@revature.net)
 * Last Modified Date: 8/3/2021
 * Description: Tests for MemberAssignmentTriggerHandler
 */
@isTest
public class MemberAssignmentTriggerTest {
    
    // Sets up a party with no class requirements
    private static void singleNoClassSetup() {
        Party__c party = new Party__c();
        party.Name = 'adventurers';
        party.Accepting_New_Members__c = true;
        party.Max_Party_Size__c = 2;
        insert party;
        Guild_Member__c member = new Guild_Member__c();
        member.Name = 'Bob';
        member.Member_Email__c = 'bob@bob.bob';
        member.Artificer_Level__c = 1;
        insert member;
    }
    
    // Sets up a party with class requirements
    private static void singleClassSetup() {
        Party__c party = new Party__c();
        party.Name = 'Drarluid';
        party.Accepting_New_Members__c = true;
        party.Max_Party_Size__c = 2;
        party.Class_Requirements__c = 'Druid;Warlock';
        insert party;
        Guild_Member__c member = new Guild_Member__c();
        member.Name = 'Tom';
        member.Member_Email__c = 'bob@bob.bob';
        member.Class__c = 'Druid';
        member.Artificer_Level__c = 1;
        insert member;
    }
	
    // Test that a member can join a party that has no requirements
    @isTest
    public static void singleTest() {
        singleNoClassSetup();
        Party__c party = [SELECT id FROM Party__c LIMIT 1];
        Guild_Member__c member = [SELECT id FROM Guild_Member__c LIMIT 1];
        Member_Assignment__c ma = new Member_Assignment__c();
        ma.Guild_Member__c = member.id;
        ma.Party__c = party.id;
        insert ma;
        Member_Assignment__c newma = [SELECT Party__c, Guild_Member__c FROM Member_Assignment__c LIMIT 1];
        system.assertEquals(member.id, newma.guild_member__c);
        system.assertEquals(party.id, newma.party__c);
    }
    
    // Test that a member can join a party that has requirements
    @isTest static void classTest() {
        singleClassSetup();
        Party__c party = [SELECT id FROM Party__c WHERE Name = 'Drarluid' LIMIT 1];
        Guild_Member__c member = [SELECT id FROM Guild_Member__c WHERE Name = 'Tom' LIMIT 1];
        Member_Assignment__c ma = new Member_Assignment__c();
        ma.Guild_Member__c = member.id;
        ma.Party__c = party.id;
        insert ma;
        Member_Assignment__c newma = [SELECT Party__c, Guild_Member__c FROM Member_Assignment__c LIMIT 1];
        system.assertEquals(member.id, newma.guild_member__c);
        system.assertEquals(party.id, newma.party__c);
    }
    
}