Project1/force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/Guild_Hall__c.field-meta.xml
<CustomField>
    <fullName>Guild_Hall__c</fullName>
    <label>Guild Hall</label>
    <referenceTo>Guild_Hall__c</referenceTo>
    <relationshipLabel>Facilities</relationshipLabel>
    <relationshipName>Facilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Facility__c/fields/Supported_Skills__c.field-meta.xml
<CustomField>
    <fullName>Supported_Skills__c</fullName>
    <inlineHelpText>What does this facility enable people to do?</inlineHelpText>
    <label>Supported Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skills</valueSetName>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Guild_Hall__c/Guild_Hall__c.object-meta.xml
<CustomObject>
    <label>Guild Hall</label>
    <nameField>
        <label>Guild Hall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Halls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Hall__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location of the guild hall.</description>
    <label>Location</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/Quest__c.object-meta.xml
<CustomObject>
    <label>Quest</label>
    <nameField>
        <label>Quest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Quest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quests</relationshipLabel>
    <relationshipName>Quests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Danger_Level__c.field-meta.xml
<CustomField>
    <fullName>Danger_Level__c</fullName>
    <description>This field describes the difficulty of a quest.</description>
    <label>Danger Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certain Death</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Beginner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Date_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Opened__c</fullName>
    <description>The date that quest became available for completion.</description>
    <label>Date Opened</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Guild_Hall__c.field-meta.xml
<CustomField>
    <fullName>Guild_Hall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Hall</label>
    <referenceTo>Guild_Hall__c</referenceTo>
    <relationshipLabel>Quests</relationshipLabel>
    <relationshipName>Quests</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_City__c.field-meta.xml
<CustomField>
    <fullName>Quest_City__c</fullName>
    <description>The city affiliated with this quest.</description>
    <label>Quest City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quest__c/fields/Quest_Country__c.field-meta.xml
<CustomField>
    <fullName>Quest_Country__c</fullName>
    <description>The country affiliated with this quest.</description>
    <label>Quest Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quest__c/fields/Quest_Details__c.field-meta.xml
<CustomField>
    <fullName>Quest_Details__c</fullName>
    <label>Quest Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Quest_Postal_Code__c</fullName>
    <description>The postal code of the quest-giver.</description>
    <label>Quest Postal Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_State__c.field-meta.xml
<CustomField>
    <fullName>Quest_State__c</fullName>
    <description>The home state of the quest-giver.</description>
    <label>Quest State</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Quest_Street__c.field-meta.xml
<CustomField>
    <fullName>Quest_Street__c</fullName>
    <description>The street address of the quest-giver.</description>
    <label>Quest Street</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Required_Professions__c.field-meta.xml
<CustomField>
    <fullName>Required_Professions__c</fullName>
    <label>Required Professions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventurer</fullName>
            </value>
            <value>
                <fullName>Craftsman</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <description>The sub-status of a quest&apos;s completion.</description>
    <label>Sub-Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Never</fullName>
            </value>
            <value>
                <fullName>Gonna</fullName>
            </value>
            <value>
                <fullName>Give</fullName>
            </value>
            <value>
                <fullName>You</fullName>
            </value>
            <value>
                <fullName>Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/globalValueSets/Skills.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Athletics</fullName>
    </customValue>
    <customValue>
        <fullName>Acrobatics</fullName>
    </customValue>
    <customValue>
        <fullName>Sleight of Hand</fullName>
    </customValue>
    <customValue>
        <fullName>Stealth</fullName>
    </customValue>
    <customValue>
        <fullName>Arcana</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Investigation</fullName>
    </customValue>
    <customValue>
        <fullName>Nature</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Handling</fullName>
    </customValue>
    <customValue>
        <fullName>Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Perception</fullName>
    </customValue>
    <customValue>
        <fullName>Survival</fullName>
    </customValue>
    <customValue>
        <fullName>Deception</fullName>
    </customValue>
    <customValue>
        <fullName>Intimidation</fullName>
    </customValue>
    <customValue>
        <fullName>Performance</fullName>
    </customValue>
    <customValue>
        <fullName>Persuasion</fullName>
    </customValue>
    <customValue>
        <fullName>Alchemy</fullName>
    </customValue>
    <customValue>
        <fullName>Brewing</fullName>
    </customValue>
    <customValue>
        <fullName>Calligraphy</fullName>
    </customValue>
    <customValue>
        <fullName>Carpentry</fullName>
    </customValue>
    <customValue>
        <fullName>Cartography</fullName>
    </customValue>
    <customValue>
        <fullName>Cobbling</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Glassblowing</fullName>
    </customValue>
    <customValue>
        <fullName>Jeweling</fullName>
    </customValue>
    <customValue>
        <fullName>Leatherworking</fullName>
    </customValue>
    <customValue>
        <fullName>Masonry</fullName>
    </customValue>
    <customValue>
        <fullName>Painting</fullName>
    </customValue>
    <customValue>
        <fullName>Pottery</fullName>
    </customValue>
    <masterLabel>Skills</masterLabel>
</GlobalValueSet>

Project1/force-app/main/default/classes/GuildExtensionTest.cls
// 92% test coverage for GuildExtension
@isTest
public class GuildExtensionTest {
    
    // guild hall negative test
    @isTest 
    static void testGuildHallNoLocation(){    
        Guild_Hall__c gh = new Guild_Hall__c(Name = 'Test Guild Hall');   
        Database.SaveResult sr = database.insert(gh, false);   
        
        List<Guild_Hall__c> guilds = [SELECT Id, name FROM Guild_Hall__c];
        
        PageReference testPage = Page.GuildHallListPage; 
        Test.setCurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(gh.Id));
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(guilds);
        GuildExtension ext = new GuildExtension(ssc);         
        
        System.debug(ext.getGuildList()); 
        List<Guild_Hall__c> al = [Select Name from Guild_Hall__c where Name LIKE '%Test%' LIMIT 1];
        System.assert(!sr.isSuccess());
    } 
    // guild hall one
    @isTest 
    static void testGuildHallInsertOne(){    
        Guild_Hall__c gh = new Guild_Hall__c(Name = 'Test Guild Hall', Location__c = 'Realm');   
        database.insert(gh, true);   
        
        List<Guild_Hall__c> guilds = [SELECT Id, name FROM Guild_Hall__c];
        
        PageReference testPage = Page.GuildHallListPage; 
        Test.setCurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(gh.Id));
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(guilds);
        GuildExtension ext = new GuildExtension(ssc);         
        
        System.debug(ext.getGuildList()); 
        List<Guild_Hall__c> al = [Select Name from Guild_Hall__c where Name LIKE '%Test%' LIMIT 1];
        System.assertEquals(1, al.size());
    } 
    // guild hall bulk
    @isTest 
    static void testGuildHallInsertBulk(){    
        Guild_Hall__c gh = new Guild_Hall__c(Name = 'Test Guild Hall', Location__c = 'Realm');  
        Guild_Hall__c gh2 = new Guild_Hall__c(Name = 'Test Guild Hall2', Location__c = 'Realm2');  
        database.insert(gh, true);
        database.insert(gh2, true);
        
        List<Guild_Hall__c> guilds = [SELECT Id, name FROM Guild_Hall__c];
        
        PageReference testPage = Page.GuildHallListPage; 
        Test.setCurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(gh.Id));
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(guilds);
        GuildExtension ext = new GuildExtension(ssc);         
        
        System.debug(ext.getGuildList()); 
        List<Guild_Hall__c> al = [Select Name from Guild_Hall__c where Name LIKE '%Test%' LIMIT 2];
        System.assertEquals(2, al.size());
    } 
    
    
    
    
    // facility negative test
        @isTest 
    	static void testFacilitiesNoLocation(){    
        Facility__c f = new Facility__c(Name = 'Test Guild Hall');   
        Database.SaveResult sr = database.insert(f, false);   
        
        List<Facility__c> facs = [SELECT Id, name FROM Facility__c];
        
        PageReference testPage = Page.GuildHallPage; 
        Test.setCurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(f.Id));
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(facs);
        GuildExtension ext = new GuildExtension(ssc);         
        
        System.debug(ext.getFacilities()); 
        List<Facility__c> al = [Select Name from Facility__c where Name LIKE '%Test%' LIMIT 1];
        System.assert(!sr.isSuccess());
    } 
    // facility insert one test
    @isTest 
    static void testFacilityInsertOne(){  
        Guild_Hall__c testHall = new Guild_Hall__c(Name = 'Test Guild Hall', Location__c = 'testRealm');
        database.insert(testHall, true);
        
        Facility__c f = new Facility__c(Name = 'Test Facility',Guild_Hall__c=testHall.Id, Supported_Skills__c='Cartography');   
        database.insert(f, true);   
        
        List<Facility__c> facilities = [SELECT Id, name FROM Facility__c];
        
        PageReference testPage = Page.GuildHallPage; 
        Test.setCurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(f.Id));
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(facilities);
        GuildExtension ext = new GuildExtension(ssc);         
        
        System.debug(ext.getFacilities()); 
        List<Facility__c> al = [Select Name from Facility__c where Name LIKE '%Test%' LIMIT 1];
        System.assertEquals(1, al.size());
    } 
    // facility insert bulk test
    @isTest 
    static void testFacilitiesInsertBulk(){ 
        Guild_Hall__c testHall = new Guild_Hall__c(Name = 'Test Guild Hall', Location__c = 'testRealm');
        database.insert(testHall, true);
        Facility__c f = new Facility__c(Name = 'Test Guild Hall', Guild_Hall__c=testHall.Id, Supported_Skills__c='Sleight of Hand');  
        Facility__c f2 = new Facility__c(Name = 'Test Guild Hall2', Guild_Hall__c=testHall.Id, Supported_Skills__c='Cartography');  
        database.insert(f, true);
        database.insert(f2, true);
        
        List<Facility__c> guilds = [SELECT Id, name FROM Facility__c];
        
        PageReference testPage = Page.GuildHallPage; 
        Test.setCurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(f.Id));
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(guilds);
        GuildExtension ext = new GuildExtension(ssc);         
        
        System.debug(ext.getFacilities()); 
        List<Facility__c> al = [Select Name from Facility__c where Name LIKE '%Test%' LIMIT 2];
        System.assertEquals(2, al.size());
    } 
    
    
    
    
    // quest insert one test
    @isTest 
    static void testQuestInsertOne(){   
        
        Contact c = new Contact(FirstName = 'test', LastName = 'LastTest');
        database.insert(c,true);
        
        date testDate = date.newInstance(2021, 05, 12);
        Quest__c q = new Quest__c(Name = 'Test Quest', Quest_Details__c = 'Go kill something now fool', Date_Opened__c=testDate, Location__c='Realm', Quest_City__c='Place',
                                 Danger_Level__c='Hard', Quest_Country__c='HerePlace', Quest_Postal_Code__c='46218', Quest_State__c='state', Quest_Street__c='123 herestreet',
                                 Required_Professions__c='Adventurer', Reward__c=100, Status__c='New', Sub_Status__c='Pending',Contact__c=c.id);   
        database.insert(q, true);   
        
        
        List<Quest__c> quests = [SELECT Id, name FROM Quest__c];
        
        PageReference testPage = Page.GuildHallPage; 
        Test.setCurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(q.Id));
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(quests);
        GuildExtension ext = new GuildExtension(ssc);         
        
        System.debug(ext.getQuest()); 
        List<Quest__c> al = [Select Name from Quest__c where Name LIKE '%Test%' LIMIT 1];
        System.assertEquals(1, al.size());
    } 
    // quest insert bulk test
    @isTest 
    static void testQuestInsertBulk(){   
        
        Contact c = new Contact(FirstName = 'test', LastName = 'LastTest');
        database.insert(c,true);
        
        date testDate = date.newInstance(2021, 05, 12);
        Quest__c q = new Quest__c(Name = 'Test Quest', Quest_Details__c = 'Go kill something now fool', Date_Opened__c=testDate, Location__c='Realm', Quest_City__c='Place',
                                 Danger_Level__c='Hard', Quest_Country__c='HerePlace', Quest_Postal_Code__c='46218', Quest_State__c='state', Quest_Street__c='123 herestreet',
                                 Required_Professions__c='Adventurer', Reward__c=100, Status__c='New', Sub_Status__c='Pending',Contact__c=c.id);   
         Quest__c q2 = new Quest__c(Name = 'Test2 Quest', Quest_Details__c = 'Go2 kill something now fool', Date_Opened__c=testDate, Location__c='Realm2', Quest_City__c='Place2',
                                 Danger_Level__c='Hard', Quest_Country__c='HerePl2ace', Quest_Postal_Code__c='45218', Quest_State__c='stat2e', Quest_Street__c='123 herestree2t',
                                 Required_Professions__c='Adventurer', Reward__c=1020, Status__c='New', Sub_Status__c='Pending',Contact__c=c.id); 
        database.insert(q, true);
        database.insert(q2, true);
        
        
        List<Quest__c> quests = [SELECT Id, name FROM Quest__c];
        
        PageReference testPage = Page.GuildHallPage; 
        Test.setCurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(q.Id));
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(quests);
        GuildExtension ext = new GuildExtension(ssc);         
        
        System.debug(ext.getQuest()); 
        List<Quest__c> al = [Select Name from Quest__c where Name LIKE '%Test%' LIMIT 2];
        System.assertEquals(2, al.size());
    }
    // quest negative test
    @isTest 
    static void testQuestNoRequired(){    
        Quest__c q = new Quest__c(Name = 'Test Guild Hall');   
        Database.SaveResult sr = database.insert(q, false);   
        
        List<Quest__c> quests = [SELECT Id, name FROM Quest__c];
        
        PageReference testPage = Page.GuildHallPage; 
        Test.setCurrentPage(testPage);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(q.Id));
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(quests);
        GuildExtension ext = new GuildExtension(ssc);         
        
        System.debug(ext.getQuest()); 
        List<Quest__c> al = [Select Name from Quest__c where Name LIKE '%Test%' LIMIT 1];
        System.assert(!sr.isSuccess());
    } 
}