Project1/force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/Guild_Hall__c.field-meta.xml
<CustomField>
    <fullName>Guild_Hall__c</fullName>
    <label>Guild Hall</label>
    <referenceTo>Guild_Hall__c</referenceTo>
    <relationshipLabel>Facilities</relationshipLabel>
    <relationshipName>Facilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Hall__c/Guild_Hall__c.object-meta.xml
<CustomObject>
    <label>Guild Hall</label>
    <nameField>
        <label>Guild Hall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Halls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Hall__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location of the guild hall.</description>
    <label>Location</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Quest__c/Quest__c.object-meta.xml
<CustomObject>
    <label>Quest</label>
    <nameField>
        <label>Quest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Quest__c/fields/Danger_Level__c.field-meta.xml
<CustomField>
    <fullName>Danger_Level__c</fullName>
    <description>This field describes the difficulty of a quest.</description>
    <label>Danger Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certain Death</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Beginner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Date_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Opened__c</fullName>
    <description>The date that quest became available for completion.</description>
    <label>Date Opened</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Guild_Hall__c.field-meta.xml
<CustomField>
    <fullName>Guild_Hall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Hall</label>
    <referenceTo>Guild_Hall__c</referenceTo>
    <relationshipLabel>Quests</relationshipLabel>
    <relationshipName>Quests</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Quests</relationshipLabel>
    <relationshipName>Quests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quest__c/fields/Quest_Details__c.field-meta.xml
<CustomField>
    <fullName>Quest_Details__c</fullName>
    <label>Quest Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Required_Professions__c.field-meta.xml
<CustomField>
    <fullName>Required_Professions__c</fullName>
    <label>Required Professions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventurer</fullName>
            </value>
            <value>
                <fullName>Craftsman</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Requires_Party__c.field-meta.xml
<CustomField>
    <fullName>Requires_Party__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Party</label>
    <type>Checkbox</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project1/force-app/main/default/objects/Quest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1/force-app/main/default/classes/GuildExtension.cls
// extension to query for the related objects
public with sharing class GuildExtension {
    public static integer PageSize{get;set;}
    ApexPages.StandardSetController setCon;
    public List<Quest__c> questBoard = new List<Quest__c>();
    public List<facility__c> facilityName = new List<Facility__c>();
    public List<Party__c> partyName = new List<Party__c>();
    
    // constructor
    public GuildExtension(ApexPages.StandardSetController controller){
        PageSize = 10;
        setCon = controller;
        setCon.setPageSize(PageSize);
    }
    
    // get method for facility
    public List<Facility__c> getFacilities(){
        facilityName = [SELECT Id, Name FROM Facility__c LIMIT 10];
        return facilityName;
    }

    // get method for guild name
    public Guild_Hall__c getGuildName(){
        return [SELECT Id, Name FROM Guild_Hall__c LIMIT 10];
    }
    
    
    // get method for quests
     public List<Quest__c> getQuest(){
        questBoard = [SELECT Id, Name, Danger_Level__c, Date_Opened__c, Location__c, 
                     Required_Professions__c, Reward__c, Status__c, Requires_Party__c, Quest_Details__c FROM Quest__c LIMIT 10];
         return questBoard;
        }
    
        // get method for parties
       public List<Party__c> getParty(){
        partyName = [SELECT Id, Name FROM Party__c LIMIT 10];
           return partyName;
        }
}