Project1/force-app/main/default/objects/Guild_Hall__c/Guild_Hall__c.object-meta.xml
<CustomObject>
    <label>Guild Hall</label>
    <nameField>
        <label>Guild Hall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Halls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Hall__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location of the guild hall.</description>
    <label>Location</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Artificer_Level__c.field-meta.xml
<CustomField>
    <fullName>Artificer_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Artificer Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Bard_Level__c.field-meta.xml
<CustomField>
    <fullName>Bard_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bard Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Guild_Hall__c.field-meta.xml
<CustomField>
    <fullName>Guild_Hall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Hall</label>
    <referenceTo>Guild_Hall__c</referenceTo>
    <relationshipLabel>Guild Members</relationshipLabel>
    <relationshipName>Guild_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Member_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Member Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/Total_Level__c.field-meta.xml
<CustomField>
    <fullName>Total_Level__c</fullName>
    <formula>Artificer_Level__c +  Barbarian_Level__c + Bard_Level__c + Cleric_Level__c + Druid_Level__c + Fighter_Level__c + Monk_Level__c + Paladin_Level__c + Ranger_Level__c + Rogue_Level__c + Sorcerer_Level__c + Warlock_Level__c + Wizard_Level__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project1/force-app/main/default/objects/Guild_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Guild_Member_Record</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Guild_Hall__c.field-meta.xml
<CustomField>
    <fullName>Guild_Hall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Hall</label>
    <referenceTo>Guild_Hall__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Item__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/Member_Assignment__c.object-meta.xml
<CustomObject>
    <label>Member Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Member Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Guild_Member__c.field-meta.xml
<CustomField>
    <fullName>Guild_Member__c</fullName>
    <label>Guild Member</label>
    <referenceTo>Guild_Member__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Member_Assignment__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Member Assignments</relationshipLabel>
    <relationshipName>Member_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project1/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/force-app/main/default/classes/UserPageTest.cls
@isTest
public class UserPageTest {
	@testSetup
    public static void setup(){
        Guild_Hall__c th = new Guild_Hall__c();
        th.Name = 'Test Hall';
        th.Location__c = 'The city of Testville';
        
        Guild_Hall__c th2 = new Guild_Hall__c();
        th2.Name = 'Test Hall 2';
        th2.Location__c = 'The city of Testville 2';
        
        insert th;
        insert th2;
        
        Guild_Hall__c gh = [SELECT ID
                           FROM Guild_Hall__c
                           WHERE Guild_Hall__c.ID =: th.Id];
               
        Guild_Member__c tm = new Guild_Member__c();
        tm.Name = 'testy';
        tm.Member_Email__c = 'testy@test.com';
        tm.Guild_Hall__c = gh.Id;
        tm.Artificer_Level__c = 1;
        tm.User__c = userInfo.getUserId();
        
        insert tm;
        
        Guild_Member__c gm = [SELECT ID 
                              FROM Guild_Member__c
                              WHERE Guild_Member__c.ID =: tm.ID];
        
        Party__c tp = new Party__c();
        tp.Name = 'TestParty';
        
        insert tp;
        
        Party__c party = [SELECT ID
                          FROM Party__c
                          WHERE ID =: tp.ID];
        
        item__c ti = new Item__c();
        ti.name = 'TestItem';
        ti.Guild_Member__c = gm.ID;
        
        insert ti;
        
        Member_Assignment__c ma = new Member_Assignment__c();
		ma.Guild_Member__c = gm.Id;
        ma.Party__c = party.Id;
        
        insert ma;
    }
    
    @isTest
    public static void levelUpTest(){
        Guild_Member__c gm = [SELECT ID, Artificer_Level__c, Bard_Level__c 
                              FROM Guild_Member__c 
                              WHERE Guild_Member__c.Member_Email__c = 'testy@test.com'];
        gm.Artificer_Level__c = 2;
        gm.Bard_Level__c =1 ;
        update gm;
        
        Guild_Member__c lvl = [SELECT ID, Total_Level__c 
                               FROM Guild_Member__c 
                               WHERE Guild_Member__c.ID =: gm.Id];
        
        system.assertEquals(3, lvl.Total_Level__c);
    }
    
    @isTest
    public static void levelFailureTest(){
        Guild_Member__c gm = [SELECT ID, Artificer_Level__c, Total_Level__c 
                              FROM Guild_Member__c 
                              WHERE Guild_Member__c.Member_Email__c = 'testy@test.com'];
        gm.Artificer_Level__c = -1;
        
        Database.SaveResult sr = Database.update(gm, false);
       	System.assert(!sr.isSuccess());
        
        gm.Artificer_Level__c = 0;
        
        Database.SaveResult sr2 = Database.update(gm, false);
       	System.assert(!sr2.isSuccess());
    }
    
    @isTest
    public static void guildHallChangeTest(){
        Guild_Member__c gm = [SELECT ID, Guild_Hall__c
                             FROM Guild_Member__c
                             WHERE Guild_Member__c.Member_Email__c = 'testy@test.com'];
        
        Guild_Hall__c gh2 = [SELECT ID, name
                           FROM Guild_Hall__c
                           WHERE Guild_Hall__c.Location__c =: 'The city of Testville 2'];
        
        gm.Guild_Hall__c = gh2.Id;
        update gm;
        
        Guild_Member__c hall = [SELECT ID, Guild_Hall__c
                               FROM Guild_Member__c
                               WHERE Guild_Member__c.ID =: gm.Id];
        
        system.assertEquals(gh2.id, hall.Guild_Hall__c);
    }
    
    @isTest
    public static void testUserPageController(){
        UserPageController uCon = new UserPageController();
        Guild_Member__c gm = [SELECT ID 
                              FROM Guild_Member__c 
                              WHERE Guild_Member__c.Member_Email__c = 'testy@test.com'];
        uCon.Member.id = gm.Id;
        system.assertEquals('testy' ,uCon.member.Name);
    }
    
    @isTest
    public static void testControllerSave(){
        UserPageController uCon = new UserPageController();
        Guild_Member__c gm = [SELECT ID 
                              FROM Guild_Member__c 
                              WHERE Guild_Member__c.Member_Email__c = 'testy@test.com'];
        uCon.Member.id = gm.Id;
        uCon.Member.Artificer_Level__c = 3;
        uCon.save();
        
        Guild_Member__c gm2 = [SELECT ID, Total_Level__c
                              FROM Guild_Member__c 
                              WHERE Guild_Member__c.Member_Email__c = 'testy@test.com'];
        
        system.assertEquals(3 ,gm2.Total_Level__c);
    }
    
    @isTest
    public static void testControllerSaveFailure(){
        UserPageController uCon = new UserPageController();
        Guild_Member__c gm = [SELECT ID 
                              FROM Guild_Member__c 
                              WHERE Guild_Member__c.Member_Email__c = 'testy@test.com'];
        uCon.Member.id = gm.Id;
        uCon.Member.Artificer_Level__c = -3;
        try{
            uCon.save();
            system.assert(False);
        }catch(DMLException e){
            system.assert(True);
        } 
    }
}